server:
  port: 2020
spring:
  profiles: live
  custardmysql:
    datasource:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://custard-prod.cluster-c2vxiw9jmmgp.ap-northeast-1.rds.amazonaws.com:3306/gamecraft?serverTimezone=UTC
        username: custard_admin
        password: Custard19)#
        connectionTimeout: 30000    # 풀에서 커넥션을 구하는 대기 시간
        maxLifetime: 1800000  # 풀에서 유지할 유휴 커넥션의 최대 수명시간 (사용중이 커넥션은 영향 없음)
        idleTimeout: 600000   # 커넥션이 풀에서 유휴 상태로 남을 수 있는 최대 시간 (minimumIdle < maximumPoolSize 일때만 적용됨)
        maximumPoolSize: 10 # 풀에 유지할 커넥션 최대 수 (유휴+사용중)
        minimumIdle: 5      # 풀에 유지할 커넥션 최소 수 (유휴)
        leakDetectionThreshold: 60000   # 커넥션이 풀에서 벗어날 수 있는 대기 시간
  rebuildmysql:
    datasource:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://custard-prod-rebuild.cluster-c2vxiw9jmmgp.ap-northeast-1.rds.amazonaws.com:3306/gamecraft?serverTimezone=UTC
        username: custard_admin
        password: Custard19)#
        connectionTimeout: 30000    # 풀에서 커넥션을 구하는 대기 시간
        maxLifetime: 1800000  # 풀에서 유지할 유휴 커넥션의 최대 수명시간 (사용중이 커넥션은 영향 없음)
        idleTimeout: 600000   # 커넥션이 풀에서 유휴 상태로 남을 수 있는 최대 시간 (minimumIdle < maximumPoolSize 일때만 적용됨)
        maximumPoolSize: 10 # 풀에 유지할 커넥션 최대 수 (유휴+사용중)
        minimumIdle: 5      # 풀에 유지할 커넥션 최소 수 (유휴)
        leakDetectionThreshold: 60000   # 커넥션이 풀에서 벗어날 수 있는 대기 시간
  denmamysql:
    datasource:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://db-readonly.denma.ggportal.net:3306/handhistory?serverTimezone=UTC
        username: denma
        password: password
        connectionTimeout: 30000    # 풀에서 커넥션을 구하는 대기 시간
        maxLifetime: 1800000  # 풀에서 유지할 유휴 커넥션의 최대 수명시간 (사용중이 커넥션은 영향 없음)
        idleTimeout: 600000   # 커넥션이 풀에서 유휴 상태로 남을 수 있는 최대 시간 (minimumIdle < maximumPoolSize 일때만 적용됨)
        maximumPoolSize: 10 # 풀에 유지할 커넥션 최대 수 (유휴+사용중)
        minimumIdle: 5      # 풀에 유지할 커넥션 최소 수 (유휴)
        leakDetectionThreshold: 60000   # 커넥션이 풀에서 벗어날 수 있는 대기 시간
  denmamysqlwrite:
    datasource:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://db.denma.ggportal.net:3306/handhistory?serverTimezone=UTC
        username: denma
        password: password
        connectionTimeout: 30000    # 풀에서 커넥션을 구하는 대기 시간
        maxLifetime: 1800000  # 풀에서 유지할 유휴 커넥션의 최대 수명시간 (사용중이 커넥션은 영향 없음)
        idleTimeout: 600000   # 커넥션이 풀에서 유휴 상태로 남을 수 있는 최대 시간 (minimumIdle < maximumPoolSize 일때만 적용됨)
        maximumPoolSize: 10 # 풀에 유지할 커넥션 최대 수 (유휴+사용중)
        minimumIdle: 5      # 풀에 유지할 커넥션 최소 수 (유휴)
        leakDetectionThreshold: 60000   # 커넥션이 풀에서 벗어날 수 있는 대기 시간
  phoenix:
    url: jdbc:phoenix:thin:url=http://internal.hadoop-master.denma.ggportal.net:8765;serialization=PROTOBUF